### ISSUE TITLE
Implement Copy to clipboard Function

### ISSUE THREAD

**Issue by n-ce** [n-ce/HexaDexa#5]
### Introduce a copy button which on click , output gets copied.

**Comment by TheCodinggDude** [comment]
Hey @n-ce ! Can I work on this issue ?

**Comment by TheCodinggDude** [comment]
I've added the Copy to Clipboard button. 
Deployment link :- https://thecodinggdude.github.io/HexaDexa/

**Comment by n-ce** [comment]
A SVG outlined icon instead of the emoji would do it.
Thank you for the changes!
